### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by hutber** [AdamGleave/elgato-camlink-workaround#2]
Hey Adam, sorry for such a post, but I thought for such a handy thing I should ask :)

I've python3 installed:
hutber@hutber:/mnt/googledrive/Documents/sh$ python3 --version
Python 3.8.5

But am receiving the following errors, so thought I'd drop in and see if you've any ideas or its a real error?

Mint 20.1

```
Traceback (most recent call last):
  File "./camlink.py", line 104, in <module>
    main()
  File "./camlink.py", line 99, in main
    setup_loopback()
  File "./camlink.py", line 60, in setup_loopback
    dummy_device = find_device(v4l2_output, "Dummy video device (0x0000)")
  File "./camlink.py", line 30, in find_device
    raise ValueError("Did not find a device named {name}")
ValueError: Did not find a device named {name}

```

**Comment by AdamGleave** [comment]
Sounds like `v4l2loopback` is either not installed or not loaded as a kernel module. I believe this should work:

```
sudo modprobe v4l2loopback devices=1 exclusive_caps=1
```

You can put it in `/etc/modules` to make loading it automatic.

**Comment by hutber** [comment]
Thanks Adam :)

I believe I have it enabled, but I understand what you're saying. The only way the script wouldn't work is due to these modules not being enabled.

```
hutber@hutber:/mnt/googledrive/Documents/sh$ sudo modprobe v4l2loopback devices=1 exclusive_caps=1
hutber@hutber:/mnt/googledrive/Documents/sh$ ./camlink.py 
Traceback (most recent call last):
  File "./camlink.py", line 104, in <module>
    main()
  File "./camlink.py", line 99, in main
    setup_loopback()
  File "./camlink.py", line 60, in setup_loopback
    dummy_device = find_device(v4l2_output, "Dummy video device (0x0000)")
  File "./camlink.py", line 30, in find_device
    raise ValueError("Did not find a device named {name}")
ValueError: Did not find a device named {name}

```

For confirmation of my packages installed


```
ffmpeg is already the newest version (7:4.2.4-1ubuntu0.1).
v4l2loopback-dkms is already the newest version (0.12.3-1ubuntu0.3).
v4l2loopback-utils is already the newest version (0.12.3-1ubuntu0.3).
```

**Comment by AdamGleave** [comment]
Interesting, what's the output of `v4l2-ctl --list-devices`? Do you see "Dummy video device" listed?

**Comment by hutber** [comment]
:) 

'GoproLinux' (platform:v4l2loopback-000):
	/dev/video42

HD Pro Webcam C920 (usb-0000:00:14.0-9):
	/dev/video0
	/dev/video1

**Comment by AdamGleave** [comment]
OK, well `platform:v4l2loopback-000` is the right thing but it seems to be called `'GoproLinux'` on your system for some reason -- I suspect there's a config file somewhere setting this? I think it'll work if you just replace`"Dummy video device (0x0000)"` with `"v4l2loopback"` though.

**Comment by hutber** [comment]
Ahh, interesting, Goprolinux is a video i created to be able to use my gopro as a webcam.

I'm right in thinking that if `v4l2loopback-000` is taken we could move `v4l2loopback-0000` for example?

**Comment by qrkourier** [comment]
The script works fine if the dummy device has a device number that's not zero e.g. /dev/video5. It just needs to have a predictable name for the script to look up the device number. The name "Dummy video device (0x0000)" is a fine default, but it's not safe to assume that the device name exists just because the v4l2loopback module was loaded. 

For example, In a case where the module was already being loaded for some other purpose, there may already be a loopback device with some other name. It's easy enough to modify the module loading invocation to include the expected name. In my case, I was already using v4l2loopback with the OBS virtual cam, and so I needed to modify my module loading command like this.

```bash
# before
sudo modprobe v4l2loopback devices=1 card_label="OBSCam" exclusive_caps=1

# after
sudo modprobe v4l2loopback devices=2 card_label="OBSCam","Dummy video device (0x0000)" exclusive_caps=1
```

Reference: https://github.com/umlaeute/v4l2loopback
